version: '3.8'
services:
  gateway:
    build:
      context: docker/app-dev
    volumes:
      - ./internal:/internal
    working_dir: /internal/reverse-proxy
    ports:
      - "127.0.0.1:5000:$PORT"
    env_file:
      - .env